version: '3.7'
services:
    mysql:
        image: mysql
        restart: always
        environment:
          MYSQL_DATABASE: 'db'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'user'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'password'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - '3306:3306'
        volumes:
          - ./my-db:/var/lib/mysql
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    iris:
      build: 
        context: .
        dockerfile: Dockerfile
      restart: always
      ports: 
        - 1972:1972
        - 52773:52773
        - 53773:53773
      volumes:
        - ./:/irisrun/repo